version: '3'
services:
  db:
    container_name: contact_book_dev_db
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=contact_book_db